### ISSUE TITLE
"pip install thampi" fails

### ISSUE THREAD

**Issue by AlissonRS** [scoremedia/thampi#12]
When I try  to run `pip install thampi`, it fails with this message:

> cfn-flip 1.1.0.post1 has requirement PyYAML>=3.13b1, but you’ll have pyyaml 3.12 which is incompatible.

So I tried uninstalling PyYAML in this virtual environment (it had version 3.12 as expected), then I tried installing it manually again, however a new error message appears:

> zappa 0.45.1 has requirement PyYAML==3.12, but you'll have pyyaml 3.13 which is incompatible.
> zappa 0.45.1 has requirement Werkzeug==0.12, but you'll have werkzeug 0.14.1 which is incompatible.

How can we fix that?

**Comment by RAbraham** [comment]
Hi,
Can you show me your `requirements.txt` file? i.e. what other libraries do you have outside `thampi` in your project?

**Comment by RAbraham** [comment]
does it fail if you create a new virtual environment from scratch and `pip install thampi`?

**Comment by RAbraham** [comment]
so I get the same "error"  when I install from scratch but my installation continues. Does your installation fail? I can continue and and run `python train.py` as in the tutorial.

**Comment by RAbraham** [comment]
@AlissonRS let me know if you are blocked. If not, I'll close this issue.
